# Generated by Django 5.2.3 on 2025-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100, unique=True)),
                ('player1', models.CharField(blank=True, max_length=100, null=True)),
                ('player2', models.CharField(blank=True, max_length=100, null=True)),
                ('board', models.CharField(default='_________', max_length=9)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('game_state', models.CharField(choices=[('waiting', 'Waiting for Player'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('game_mode', models.CharField(choices=[('player', 'Player vs Player'), ('bot_easy', 'Player vs Bot (Easy)'), ('bot_hard', 'Player vs Bot (Hard)')], default='player', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
