# Generated by Django 5.2.3 on 2025-06-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_stanza', models.CharField(max_length=100, unique=True)),
                ('giocatore1', models.CharField(blank=True, max_length=100, null=True)),
                ('giocatore2', models.CharField(blank=True, max_length=100, null=True)),
                ('scacchiera', models.CharField(default='_________', max_length=9)),
                ('prossimo_turno', models.CharField(default='X', max_length=1)),
                ('stato_partita', models.CharField(choices=[('attesa', 'In attesa'), ('in_corso', 'In Corso'), ('finita', 'Finita')], default='attesa', max_length=10)),
                ('modalita_gioco', models.CharField(choices=[('player', 'Player vs Player'), ('bot_easy', 'Player vs Bot Facile'), ('bot_hard', 'Player vs Bot Difficile')], default='player', max_length=10)),
                ('vincitore', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
